"""
Initial schema from existing models

Revision ID: 58948b63e4a7
Revises: 
Create Date: 2026-03-03 15:44:41.226941

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "58948b63e4a7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
